name: wiki

on: [gollum]

jobs:
  wiki_teams_notification:
    runs-on: ubuntu-latest
    name: Wiki Teams notification
    steps:
    - uses: actions/checkout@v2
      name: Checkout
    - uses: ./.github/actions
      name: Send notification
      env:
        # A webhook URL to a Teams channel you want notifications to be sent to.
        WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
